#!/bin/sh

CFLAGS="$CFLAGS \
     -I/home/humphery/thirdparty/apr/include/apr-1  \
     -I/home/humphery/thirdparty/apr-util/include/apr-1  \
    -I/usr/include/httpd \
    -I/usr/include/libxml2 \
    -DWITH_LUA   \
    -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500 -DWITH_PCRE_JIT -DREQUEST_EARLY          -DWITH_REMOTE_RULES \
    -I/home/humphery/thirdparty/pcre-8.36/include \
    -DWITH_YAJL -I/home/humphery/thirdparty/yajl/include \
    "


CORE_LIBS="$CORE_LIBS \
     -L/home/humphery/thirdparty/apr/lib -lapr-1 \
     -L/home/humphery/thirdparty/apr-util/lib -laprutil-1 \
    -I/usr/include/httpd \
    -lcurl   \
    -lxml2 -lz -lm \
    -llua -lm -ldl   \
    -L/home/humphery/thirdparty/pcre-8.36/lib -lpcre \
    -L/usr/lib64  -lm -lpcre \
    -lyajl \
    "

ngx_addon_name=ngx_http_modsecurity

CORE_MODULES="$CORE_MODULES ngx_pool_context_module"

HTTP_AUX_FILTER_MODULES="ngx_http_modsecurity $HTTP_AUX_FILTER_MODULES"

NGX_ADDON_SRCS="$NGX_ADDON_SRCS \
		$ngx_addon_dir/ngx_http_modsecurity.c \
		$ngx_addon_dir/apr_bucket_nginx.c \
		$ngx_addon_dir/ngx_pool_context.c"

NGX_ADDON_DEPS="$NGX_ADDON_DEPS \
		$ngx_addon_dir/apr_bucket_nginx.h \
		$ngx_addon_dir/ngx_pool_context.h"

CORE_LIBS="$ngx_addon_dir/../../standalone/.libs/standalone.a $CORE_LIBS"

CORE_INCS="$CORE_INCS \
	$ngx_addon_dir \
	$ngx_addon_dir/../../standalone \
	$ngx_addon_dir/../../apache2"

