#!/bin/bash
export THIRD_PARTY_HOME=/usr/local/thirdparty
export PCRE_HOME=$THIRD_PARTY_HOME/pcre-8.36
export LUAJIT_HOME=$THIRD_PARTY_HOME/luajit
export LUAJIT_LIB=$LUAJIT_HOME/lib
export LUAJIT_INC=$LUAJIT_HOME/include/luajit-2.1
# --with-debug
./configure --http-client-body-temp-path=temp/client_body_temp --http-proxy-temp-path=temp/proxy-temp --http-fastcgi-temp-path=temp/fastcgi-temp --http-uwsgi-temp-path=temp/uwsgi-temp --http-scgi-temp-path=temp/scgi-temp

#	--add-module=modules/modsecurity-2.9.1/nginx/modsecurity --add-dynamic-module=modules/ngx_http_dyups_module --add-dynamic-module=modules/ngx_proc_luashm_module/http \

#
cp Makefile.in Makefile
cp conf/nginx.web.conf conf/nginx.conf

